import { finalizer } from 'abslink';
import { WebGL2Renderer } from './webgl-renderer';
import type { ASSEvent, ASSStyle } from '../jassub';
import type { JASSUB } from '../wasm/types.js';
interface opts {
    wasmUrl: string;
    width: number;
    height: number;
    subUrl: string | undefined;
    subContent: string | null;
    fonts: Array<string | Uint8Array>;
    availableFonts: Record<string, Uint8Array | string>;
    fallbackFont: string;
    debug: boolean;
    libassMemoryLimit: number;
    libassGlyphLimit: number;
    useLocalFonts: boolean;
}
export declare class ASSRenderer {
    _offCanvas?: OffscreenCanvas;
    _wasm: JASSUB;
    _subtitleColorSpace?: 'BT601' | 'BT709' | 'SMPTE240M' | 'FCC' | null;
    _videoColorSpace?: 'BT709' | 'BT601';
    _malloc: (size: number) => number;
    _gpurender: WebGL2Renderer;
    debug: boolean;
    useLocalFonts: boolean;
    _availableFonts: Record<string, Uint8Array | string>;
    _fontMap: Record<string, boolean>;
    _fontId: number;
    _ready: Promise<void>;
    _getFont: (font: string) => Promise<void>;
    constructor(data: opts, getFont: (font: string) => Promise<void>);
    ready(): Promise<void>;
    addFont(fontOrURL: Uint8Array | string): void;
    createEvent(event: ASSEvent): void;
    getEvents(): Partial<ASSEvent>[];
    setEvent(event: ASSEvent, index: number): void;
    removeEvent(index: number): void;
    createStyle(style: ASSStyle): import("../wasm/types.js").ASS_Style;
    getStyles(): ASSStyle[];
    setStyle(style: ASSStyle, index: number): void;
    removeStyle(index: number): void;
    styleOverride(style: ASSStyle): void;
    disableStyleOverride(): void;
    setDefaultFont(fontName: string): void;
    setTrack(content: string): void;
    freeTrack(): void;
    setTrackByUrl(url: string): void;
    _checkColorSpace(): void;
    _findAvailableFonts(font: string): void;
    _asyncWrite(font: Uint8Array | string): void;
    _allocFont(uint8: Uint8Array): void;
    _processAvailableFonts(content: string): void;
    _canvas(width: number, height: number, videoWidth: number, videoHeight: number): void;
    [finalizer](): Promise<void>;
    _draw(time: number, force?: boolean): void;
    _setColorSpace(videoColorSpace: 'RGB' | 'BT709' | 'BT601'): void;
}
export {};
